# Translation of Odoo Server.
# This file contains the translation of the following modules:
# * account_plaid
# 
# Translators:
# Boris Stefanov <borkata@gmail.com>, 2018
# preslav <hackerz99999@gmail.com>, 2016
msgid ""
msgstr ""
"Project-Id-Version: Odoo 9.0\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2015-10-01 06:30+0000\n"
"PO-Revision-Date: 2018-05-30 20:13+0000\n"
"Last-Translator: Boris Stefanov <borkata@gmail.com>\n"
"Language-Team: Bulgarian (http://www.transifex.com/odoo/odoo-9/language/bg/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: \n"
"Language: bg\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#. module: account_plaid
#: model:ir.model.fields,field_description:account_plaid.field_online_account_token
msgid "Access Token"
msgstr "Удостоверение за достъп"

#. module: account_plaid
#: code:addons/account_plaid/models/plaid.py:52
#: code:addons/account_plaid/models/plaid.py:63
#, python-format
msgid "An error has occurred while trying to connect to plaid service"
msgstr "Възникна грешка при опит за връзка с услугата plaid."

#. module: account_plaid
#: model:ir.model,name:account_plaid.model_online_account
msgid "Email Thread"
msgstr "Емейл Нишка"

#. module: account_plaid
#: code:addons/account_plaid/models/plaid.py:129
#, python-format
msgid "Error in synchronization"
msgstr "Грешка при синхронизацията"

#. module: account_plaid
#: code:addons/account_plaid/models/plaid.py:136
#, python-format
msgid "Error with Plaid.com"
msgstr "Грешка в Plaid.com"

#. module: account_plaid
#: model:ir.model,name:account_plaid.model_account_journal
msgid "Journal"
msgstr "Журнал"

#. module: account_plaid
#: model:ir.model.fields,field_description:account_plaid.field_account_journal_onlinesync_config_plaid_account_id
msgid "Online Account"
msgstr "Онлайн акаунт"

#. module: account_plaid
#: model:ir.model.fields,field_description:account_plaid.field_online_account_plaid_id
msgid "Plaid Account"
msgstr "Plaid акаунт"

#. module: account_plaid
#: model:ir.ui.view,arch_db:account_plaid.account_config_settings_view_inherit_plaid
msgid "Plaid Configuration"
msgstr "Plaid конфигурация"

#. module: account_plaid
#: model:ir.model.fields,field_description:account_plaid.field_account_config_settings_plaid_id
msgid "Plaid ID"
msgstr "Plaid ИН"

#. module: account_plaid
#: model:ir.model.fields,field_description:account_plaid.field_account_config_settings_plaid_secret
msgid "Plaid Secret"
msgstr "Plaid тайна"

#. module: account_plaid
#: code:addons/account_plaid/models/plaid.py:130
#, python-format
msgid ""
"The synchronization of the journal %s with the plaid account %s has "
"failed.<br>The error message is :<br>%s"
msgstr "Синхронизацията на журнал %s с услуга plaid%s пропадна.<br>Съобщението за грешка е :<br>%s"

#. module: account_plaid
#: code:addons/account_plaid/models/plaid.py:137
#, python-format
msgid ""
"The synchronization with Plaid.com failed. Please check the error : <br> %s"
msgstr "Синхронизацията с Plaid.com не сработи. Моля, проверете грешката : <br> %s"

#. module: account_plaid
#: code:addons/account_plaid/models/plaid.py:38
#, python-format
msgid ""
"You haven't configure your plaid account, please go to accounting/settings "
"to configure it"
msgstr "Не сте настроили своят plaid профил, моля отидете в счетоводство/настройки за да го конфигурирате"

#. module: account_plaid
#: model:ir.model,name:account_plaid.model_account_config_settings
msgid "account.config.settings"
msgstr "account.config.settings"

#. module: account_plaid
#: model:ir.model,name:account_plaid.model_account_journal_onlinesync_config
msgid "account.journal.onlinesync.config"
msgstr "account.journal.onlinesync.config"

#. module: account_plaid
#: model:ir.model,name:account_plaid.model_online_institution
msgid "online.institution"
msgstr "online.institution"
