# Translation of Odoo Server.
# This file contains the translation of the following modules:
# 	* account_ponto
# 
# Translators:
# Raphael Mendonça, 2019
# Maicon Grahl <maicongrahl@hotmail.com>, 2019
# Mateus Lopes <mateus1@gmail.com>, 2019
# grazziano <gra.negocia@gmail.com>, 2019
# mariana rodrigues <mariana12v@gmail.com>, 2019
# 
msgid ""
msgstr ""
"Project-Id-Version: Odoo Server saas~12.4+e\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2019-08-12 11:29+0000\n"
"PO-Revision-Date: 2019-08-12 13:19+0000\n"
"Last-Translator: mariana rodrigues <mariana12v@gmail.com>, 2019\n"
"Language-Team: Portuguese (Brazil) (https://www.transifex.com/odoo/teams/41243/pt_BR/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: \n"
"Language: pt_BR\n"
"Plural-Forms: nplurals=2; plural=(n > 1);\n"

#. module: account_ponto
#: code:addons/account_ponto/models/ponto.py:99
#, python-format
msgid "Account"
msgstr "Conta"

#. module: account_ponto
#: code:addons/account_ponto/models/ponto.py:78
#, python-format
msgid "An error occurred during online synchronization"
msgstr "Ocorreu um erro durante a sincronização online"

#. module: account_ponto
#: code:addons/account_ponto/models/ponto.py:196
#, python-format
msgid "Fetching transactions took too much time."
msgstr ""

#. module: account_ponto
#: model:ir.model,name:account_ponto.model_account_online_journal
msgid "Interface for Online Account Journal"
msgstr ""

#. module: account_ponto
#: code:addons/account_ponto/models/ponto.py:47
#, python-format
msgid "Invalid access token"
msgstr ""

#. module: account_ponto
#: code:addons/account_ponto/models/ponto.py:67
#, python-format
msgid "Link your Ponto account"
msgstr ""

#. module: account_ponto
#: selection:account.online.provider,provider_type:0
msgid "Plaid"
msgstr "Plaid"

#. module: account_ponto
#: selection:account.online.provider,provider_type:0
#: code:addons/account_ponto/models/ponto.py:118
#, python-format
msgid "Ponto"
msgstr ""

#. module: account_ponto
#: model:ir.model.fields,field_description:account_ponto.field_account_online_journal__ponto_last_synchronization_identifier
msgid "Ponto Last Synchronization Identifier"
msgstr ""

#. module: account_ponto
#: model:ir.model.fields,field_description:account_ponto.field_account_online_provider__ponto_token
msgid "Ponto Token"
msgstr ""

#. module: account_ponto
#: model:ir.model.fields,field_description:account_ponto.field_account_online_provider__provider_type
msgid "Provider Type"
msgstr "Tipo de provedor"

#. module: account_ponto
#: model:ir.model,name:account_ponto.model_account_online_provider
msgid "Provider for online account synchronization"
msgstr "Provedor para sincronização de contas online"

#. module: account_ponto
#: code:addons/account_ponto/models/ponto.py:55
#, python-format
msgid "Server not reachable, please try again later"
msgstr ""

#. module: account_ponto
#: model:ir.model.fields,help:account_ponto.field_account_online_provider__ponto_token
msgid "Technical field that contains the ponto token"
msgstr ""

#. module: account_ponto
#: code:addons/account_ponto/models/ponto.py:79
#, python-format
msgid "The following error happened during the synchronization: %s"
msgstr "O seguinte erro ocorreu durante a sincronização:%s"

#. module: account_ponto
#: code:addons/account_ponto/models/ponto.py:52
#, python-format
msgid "Timeout: the server did not reply within 60s"
msgstr ""

#. module: account_ponto
#: model_terms:ir.ui.view,arch_db:account_ponto.ponto_online_provider_account_form_view
msgid "Update Accounts"
msgstr ""

#. module: account_ponto
#: selection:account.online.provider,provider_type:0
msgid "Yodlee"
msgstr "Yodlee"

#. module: account_ponto
#: model:ir.model.fields,help:account_ponto.field_account_online_journal__ponto_last_synchronization_identifier
msgid "id of ponto synchronization"
msgstr ""
